### ISSUE TITLE
Edit-ui: The "goal" of edit-ui not clearly spelled out.

### ISSUE THREAD

**Issue by sconnelley** [stamen/maptcha-v2#10]
The goal is to line up the maps, right? I mean obviously you can fiddle around with this as a fun tool, but is the primary function to be able to correctly overlay the maps one on the other? If so, that should be made clear. What does “finish” mean in this context? Why would I as a user want to “finish” or, alternatively, to “Skip This Map?” What will happen?

**Comment by nvkelso** [comment]
@george08 for design help.

**Comment by george08** [comment]
Trying to de-nerdify geo-rectify... align, balance, bring into line, calibrate, connect, correct, fine-tune, fit, fix, focus, grind, improve, improve accommodate, mend, overhaul, polish, put in place, put in working order, readjust, rectify, regulate, renovate, repair, service, set, sharpen, square, square up, tighten, troubleshoot, tune up

**Comment by george08** [comment]
This feedback is understandable given the context of the testing (in a vacuum, testing the admin/upload scenario). Important to remember that the general visitor will be coming in through an external client site, in this case History Pin, where each map will be presented in the context of a "crowdsourced geo-rectification challenge," so hopefully the purpose of the UI is more explained.

But! Perhaps we could consider a layer of help text or a set of labels for everything as well.

**Comment by george08** [comment]
Have added FAQ content, and layout for a link to it in the edit UI: #33
