### ISSUE TITLE
Edit-ui: rotate wheel confusing?

### ISSUE THREAD

**Issue by sconnelley** [stamen/maptcha-v2#12]
It actually took me a while to figure out that the rotate wheel also can resize the image. When it’s a wheel, I think there’s a tendency to assume it can just rotate rather than resize. Maybe some fiddling with this icon is in order to better visually communicate its two functions (rotate and resize)?

**Comment by nvkelso** [comment]
@george08 for design help?

**Comment by george08** [comment]
I'm not too worried about this. If we were to hear many more reports of it, I will be.
