### ISSUE TITLE
Edit-ui: Some sort of instructions

### ISSUE THREAD

**Issue by sconnelley** [stamen/maptcha-v2#14]
From Miriam Pollock:
If you’re self-motivated, curious, patient, and very energetic, you can figure all this stuff out pretty easily and get yourself acclimated to the process. However, it might be nice if there were a instructions, or at least the option, for those who desire them, of opening a separate page or pop-up box with instructions. Simple instructions about the goals of the editing process and how to use the tools to achieve those goals would be very helpful.

From STEVE HINDMAN:
It would be good to give the user online help and perhaps a sample task with two maps provided by the service, so that the user understands the capabilities of the application and can have success in a controlled environment before they go off into the wild, so to speak

**Comment by george08** [comment]
FAQ

For the public tool:
- What is this thing?
- Why is it important?
- How do I do it?
- Can I save my place?
- I have some old maps I'd like to add to Maptcha. How do I do that?
- Is this open source? Can I use it at my institution?

For the upload tool:
- What is this thing?
- How do I get started?
- What's an atlas?
- Can I play with the map placement tool?
- Do you have a naming convention I should use?
- Is there a file size limit on map images?
- Is there an automated way for me to do all this?
- Can you integrate with my catalog?
- How do I get the geodata back out again?
- Can you help me display these maps on my site?

**Comment by george08** [comment]
First pass at FAQ complete. I created a librarian version and a public version. I've also added links to them, but am not sure if they work until one of the guys can deploy.
