### ISSUE TITLE
Admin: Unclear what 'edit' means & "Atlases" are?

### ISSUE THREAD

**Issue by sconnelley** [stamen/maptcha-v2#20]
From Maria Santos:
- if you suggest a naming convention it will be easier to find out what the atlas are about 
- will these be editable or at least provide comments?
- I like that you can edit the maps but I am not sure what this means, ie, what kind of edits are allowed
- when i click in Edit it shows the map overlaid with other map but again not sure what is editable

**Comment by george08** [comment]
I've created a bunch of FAQ for the admin site. Hopefully that'll help with some of this stuff.

We should rename the "EDIT" links to something more useful, like, "Map Placement" or something less lame than that.
