### ISSUE TITLE
Need Github readme + client documentation

### ISSUE THREAD

**Issue by george08** [stamen/maptcha-v2#26]
Important that this project is left well documented by the end of the year. At least a readme that describes all the system components should be written, ideally with some kind of installation instructions. 

One thing we haven't considered is what instructions/docs a client like History Pin will need to set this up at their end. Something about consuming a feed of atlases, and setting up maptcha in an iframe, etc. (Mark Frost is expecting this by Dec 21, even if it's ad hoc.)

**Comment by nvkelso** [comment]
An annotated whiteboard sketch might be useful here...

**Comment by george08** [comment]
Absolument.

**Comment by george08** [comment]
I've created a new page for the website, called docs.html, which has the sections we discussed in the meeting on 12/12/12, namely:

JSON Feed
Editing UI
Geodata
S3
Code Repository

I think the goal for this page should be to provide Mark Frost at Historypin with installation instructions for them.
Ideally, we would send a complete draft version Monday or Tuesday, and aim to finish it by end of week.

**Comment by migurski** [comment]
Edit `edit_ui/templates/docs.html`

**Comment by migurski** [comment]
Added in 3afe266.
