### ISSUE TITLE
getting studio version up & running...

### ISSUE THREAD

**Issue by sconnelley** [stamen/maptcha-v2#27]

**Comment by migurski** [comment]
Added two things to Studio:
1. /var/www/com.stamen.studio/yearofthebay/show/recent/edit_ui/yotb.sh script, run with keyword "start" or "restart"
2. /etc/crontab entry for /var/www/com.stamen.studio/yearofthebay/show/recent/worker/run.py

**Comment by nvkelso** [comment]
Visible at:
http://yotb.studio.stamen.com/
