### ISSUE TITLE
Can the map edit UI have variable width?

### ISSUE THREAD

**Issue by george08** [stamen/maptcha-v2#29]
It would be super awesome if the edit UI could always be, say, 95% wide (and left/right sections within that area split 50/50)

http://yotb.studio.stamen.com/place-rough/map/f17f6448-1ef3-11e2-901d-00259071d532

**Comment by sconnelley** [comment]
hasn't it always been this way.  Can you post an image?

**Comment by george08** [comment]
Sure:

![work-area-width](https://f.cloud.github.com/assets/354542/14608/c4062220-4655-11e2-9400-28ee20dd16b2.jpg)

Note - 1px line in bottom white area near submit buttons on the right.

**Comment by george08** [comment]
Workspace should always be as large as possible... like always 90 or 95% of the window, and centered in it. The screenshot above isn't 90%.

**Comment by sconnelley** [comment]
ok, i know what your talking about now.  I'm reworking that layout.  I'm not really liking the 'fluid' layout resizing, it's really jerky.  So I am thinking of basing the layout on fixed break points.  

If you rather not do that and stay with the fluid layout I'm fine with that as well.  Just seems a bit jerky, when sizing down.  Not much I can do with that.

**Comment by sconnelley** [comment]
edit ui now takes up approx. 95% of layout width
also the sub-pixel error should be gone, I hope
changed in e308d6c1d5baeab564b87d966ba14fe90a9ffd54
