### ISSUE TITLE
Edit UI: Refine link to FAQ page

### ISSUE THREAD

**Issue by george08** [stamen/maptcha-v2#33]
See attached. Little "FAQ" link in #3366ff, 14pt Helvetica Neue.

![maptcha-v2-faq-link](https://f.cloud.github.com/assets/354542/9680/276ee2fe-44ba-11e2-8602-85f007c759b4.png)

**Comment by george08** [comment]
Links to faq-public.html

**Comment by sconnelley** [comment]
functionally complete 00adada6f032789b75eba252a4be0be5b17c3455

**Comment by george08** [comment]
Hey - it needs to be a blue link, and closer to the Maptcha logo, per comp.

**Comment by sconnelley** [comment]
sorry George, updated in 140a3aac2dbacdace654fe9e1479eb5beb40010b
But I did add keyboard shortcuts to fine tune rough placement, try those arrow keys!
