### ISSUE TITLE
Upload: The use of Dropbox confusing 

### ISSUE THREAD

**Issue by sconnelley** [stamen/maptcha-v2#4]
From Miriam Pollock...

I actually only just downloaded Dropbox so I could test this system. I’d definitely heard of it, but I can imagine there are those out there who have no idea what it does. So maybe a quick sentence about what Dropbox is or how it works for those who don’t have it? An incitement for those who might not want to invest the time in setting up something they’re not familiar with, along the lines of “it’s very quick to download!” ?

Maybe we should change the language in the admin/upload page

**Comment by george08** [comment]
Pretty sure I edited some of this language when we first got the feedback, and checked it in, but perhaps it's not made its way to the site?

https://github.com/stamen/yearofthebay/commit/2c67ee172c7f253d0ea58013534988f80ce76b16
https://github.com/stamen/yearofthebay/commit/e961cbcfe699c80889ed6c1cb295e16a95489930
