### ISSUE TITLE
Map view doesn't work

### ISSUE THREAD

**Issue by george08** [stamen/maptcha-v2#40]
I see no map here:
http://yotb.studio.stamen.com/map-sandwich/map/de85023a-4a9f-11e2-87c8-00259071d532

**Comment by george08** [comment]
Atlas "View Tiles" page doesn't work either:
http://yotb.studio.stamen.com/map-sandwich/atlas/62b59690-4aec-11e2-87c8-00259071d532

**Comment by george08** [comment]
Or, remind me why we can't view a single old map on Toner (or Google maps)...

**Comment by sethfitz** [comment]
Additional context from Historypin:

> Getting tiles for a single map is not working (doesn't seem to work in production server either).
> http://yotb.studio.stamen.com/tile/map/de85023a-4a9f-11e2-87c8-00259071d532/11/327/792.png
> 
> However the tile_template_full property from the JSON feed led us to this link which seems to be working fine.
> http://yotb.studio.stamen.com/thing/maps/62b6a058-4aec-11e2-87c8-00259071d532/tiles/11/327/792.png
> 
> Map Sandwitch for a single map is not working too. This is probably related to the 1st issue (tested and not working on production server either).
> http://yotb.studio.stamen.com/map-sandwich/map/de85023a-4a9f-11e2-87c8-00259071d532

**Comment by sethfitz** [comment]
Problem narrowed to https://github.com/stamen/yearofthebay/blob/14d1d2bd82ec7306ebabd45c63612cebaf0629de/edit_ui/app.py#L466-L469 -- `map_dom` is not defined.  I tried defining it with `connect_domain(aws_key, aws_secret, aws_prefix+'maps')`, but SimpleDB gives me a `NoSuchDomain` error.

@sconnelley ideas?

I'm thinking that this may have been moved from SimpleDB to MySQL, so will investigate that path.

**Comment by sconnelley** [comment]
@mojodna -- Yeah, that should be:

```
conn = mysql_connection()
mysql = conn.cursor(cursor_class=MySQLCursorDict)

 if request.endpoint == "tilemap": 
        items = mysql.execute("select tiles from `%s` where name = '%s'" % (map_dom.name,id))
    elif request.endpoint == "tileatlas":
        items = mysql.execute("select tiles from `%s` where atlas='%s' and image is not null order by image desc" % (map_dom.name,id))
```

**Comment by sethfitz** [comment]
(and 5069fa8ec8863e902decb2249c3fbc8aa52a892e)

@sconnelley Can you update the instance on studio and restart it?  Jon et al are using that in addition to the one on EC2 (which I've updated).
