### ISSUE TITLE
Add a strip along the top of the DEV/studio environment

### ISSUE THREAD

**Issue by george08** [stamen/maptcha-v2#41]
We need to be super clear about which is our DEV environment, and NOT to be used for production.

Can we have a strip along the top of yotb.studio.stamen.com that reads "This is our development environment. It is in flux, and may be unreliable."

**Comment by sethfitz** [comment]
![screen shot 2013-05-23 at 9 34 04 am](https://f.cloud.github.com/assets/45/555760/9b64f9e2-c3c6-11e2-91f9-3ff2ba9a6065.png)
