### ISSUE TITLE
Upload: Language issues on upload page confusing or unclear

### ISSUE THREAD

**Issue by sconnelley** [stamen/maptcha-v2#6]
Issues from feedback:
- In the “Map Metadata Fields” list on the Upload webpage, the example units for the map dimensions are written as “centimetres.” Shouldn’t it be the American spelling, considering these are US maps? So “centimeters.” BUT in the Example CSV, the units are just written “cm,” which obviously gets rid of the spelling issue. However, this is another potential source of confusion for the user: should you spell out the units or use an abbreviation? If it doesn’t matter and comes down to user preference, then that should be made clear.
  [glo - we should use the full word in the spreadsheet, and suggest using the full unit name and not abbreviations in the instructions.]
- There should be more explanation of commas/how elements are arranged/how they are separated. How important is it that this be just so??? Is it like a bibliography, in which you have to follow some parts with a colon, some with a period, and some with a comma? Or does it not matter so much?
  [glo - I think this is because the person was editing a CSV in a text editor. I'll write some language around this to encourage people to use a spreadsheet program :) ]
- Under the explanation for Filename in “Map Metadata Fields,” it says “Even though you've told us this in the URL above, this is a very useful reconciliation field for us.” This seems kind of jargon-y; I’m guessing scholars in the field know what a “reconciliation field” is but I sure don’t. I can get an idea from the context, but are we assuming the average student will know what this is?
  [glo - I'll fix that language]
- If I don’t know a field or don’t want to put it in, should I do two commas with a blank space in between, or just pretend that field doesn’t exist and move on to the next element I am including? This isn’t very clear.
  [glo - don't edit CSVs in a text editor]
- So PlaceNames are just cities and towns? No geographical regions, forests/parks/rivers/valleys? Maybe spell that out a bit more.
- Should the CSV document be named anything in particular? Or does it not matter?
- Atlas name - do you have a naming convention that you would like to apply?
- URL of csv file - does this mean that the csv and the map tiff or jpeg file should be in the same, say, dropbox public folder?
- csv file: is there a limit in the number of characters per attribute column? or type of data (text, number, etc?)
- map file type: other than jpg and tif? Also, is there a recommended size for a map file, i.e., map resolution? Is a map file a map, or can be photographs? Could it be possible to offer an option of a dropbox folder for those that do not have one? For example guide people to log in to a specific dropbox folder online and upload their maps directly there
  [glo - interesting - maybe historypin or stanford could supply something like that. but not for now]
- Lat/long: maybe it would be useful to give an example on how people can get approximate lat longs on the web?
  [glo - good idea. Will add a link to getlatlon]
- map width and height - specify this is the physical map and not the digital
- in general specify if there are character requirements for each attribute field (caps, numbers, separators, etc)

**Comment by george08** [comment]
Resolved most of these in https://github.com/stamen/yearofthebay/commit/e49096e5dc510ac5cf67ccbdc0e8705a982a16dd

I'll address other elements in the .CSV and a new FAQ I'm writing.
