### ISSUE TITLE
Upload: CSV URL's with incorrect extensions failing and the error message not helpful

### ISSUE THREAD

**Issue by sconnelley** [stamen/maptcha-v2#7]
From Miriam Pollock....

https://www.dropbox.com/s/2t76bod0to6yxmj/CSV.docx

When I got to the final step, having made a CSV document where I inputted the information for several Bay Area maps, and tried to input the dropbox url where the CSV document was stored, I got an error message (see the screenshot below). Basically, the website is telling me that it’s not a valid url. I’m not sure what is, or why this problem is happening.

**Comment by sconnelley** [comment]
Changed error message for incorrect extension, to "Only 'csv' & 'txt' file extensions accepted."
Should we not even bother checking for this and just send it off?????

**Comment by george08** [comment]
What do you mean? Not check for the correct type of file, or?

**Comment by sconnelley** [comment]
Maybe not check for type on client side via JS.  Let back-end try to open and parse whatever they put in there.  Obviously, redirect to error page if something fails
